### ISSUE TITLE
IE is not supported

### ISSUE THREAD

**Issue by jkim485** [idies/scidrive#10]
At least inform users which browser to use.

**Comment by raddick** [comment]
What version of IE are you using? What operating system?

**Comment by dimm0** [comment]
The front page on bottom says "limited support" for IE. All other browsers are supported. Basic functions should work in IE.
What exactly is an issue?

**Comment by jkim485** [comment]
I forgot them. When I test the new deployment I will try out again.

**Comment by dmedv** [comment]
This is an issue for scidrive-ui, not scidrive. I am marking this as closed (and 'invalid' - yay!). Please post it again in scidrive-ui repository, otherwise it is confusing.
